/* Cactus🌵Byte Studios™ — Demo & Help Standard v1.0 */
(function(){
  if(window.__cactusByteDemoInstalled)return;window.__cactusByteDemoInstalled=true;
  const cfg=window.CACTUSBYTE_DEMO||{};if(!cfg.appId||!cfg.appName)return;
  const v=String(cfg.demoVersion||'1'),seenKey=`cbs_demo_seen:${cfg.appId}:${v}`,dismissedKey=`cbs_demo_dismissed:${cfg.appId}:${v}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const style=document.createElement('style');style.textContent=`.cbs-demo-trigger{border:1px solid var(--l,#17262b);background:#0b1214;color:#e5edef;border-radius:14px;padding:12px 15px;font-weight:850;cursor:pointer}.cbs-demo-backdrop{position:fixed;z-index:1000;inset:0;background:#000d;display:none;align-items:flex-end;justify-content:center;padding:16px}.cbs-demo-backdrop.open{display:flex}.cbs-demo-panel{width:min(760px,100%);max-height:90dvh;overflow:auto;background:#0a1012;border:1px solid var(--l,#17262b);border-radius:24px;padding:20px;color:#f6f8f9}.cbs-demo-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.cbs-demo-head h2{margin:0;font-size:21px}.cbs-demo-close{width:40px;height:40px;border-radius:12px;border:1px solid var(--l,#17262b);background:#10191c;color:#fff;font-size:22px}.cbs-demo-sub{color:#7c8b91;line-height:1.5;font-size:12px}.cbs-demo-placeholder{border:1px dashed #1f4b53;border-radius:16px;padding:16px;background:#071216;color:#91a1a7;font-size:12px;line-height:1.5}.cbs-demo-video{width:100%;border-radius:16px;background:#000;max-height:360px}.cbs-demo-steps{display:grid;gap:9px;margin-top:14px}.cbs-demo-step{border:1px solid #17262b;border-radius:15px;padding:13px;background:#05090a}.cbs-demo-step strong{display:block;color:#67e8f9;font-size:13px}.cbs-demo-step span{display:block;color:#91a1a7;font-size:11px;line-height:1.45;margin-top:4px}.cbs-demo-check{display:flex;gap:8px;align-items:flex-start;color:#819096;font-size:11px;line-height:1.4;margin-top:13px}.cbs-demo-actions{display:flex;gap:9px;margin-top:14px}.cbs-demo-actions button{flex:1;border-radius:14px;padding:12px 14px;font-weight:850}.cbs-demo-primary{border:0;background:linear-gradient(90deg,#67e8f9,#2dd4bf);color:#001014}.cbs-demo-secondary{border:1px solid #17262b;background:#0b1214;color:#e5edef}@media(min-width:700px){.cbs-demo-backdrop{align-items:center}}`;document.head.appendChild(style);
  const bd=document.createElement('div');bd.className='cbs-demo-backdrop';bd.innerHTML=`<section class="cbs-demo-panel" role="dialog" aria-modal="true"><div class="cbs-demo-head"><h2>How to use ${esc(cfg.appName)}</h2><button class="cbs-demo-close" aria-label="Close">×</button></div><p class="cbs-demo-sub">${esc(cfg.intro||'A fast guided walkthrough.')}</p><div class="cbs-demo-media"></div><div class="cbs-demo-steps"></div><label class="cbs-demo-check"><input type="checkbox" class="cbs-demo-dontshow"><span>Don’t show this automatically again for this demo version. Help remains available from the home screen.</span></label><div class="cbs-demo-actions"><button class="cbs-demo-secondary cbs-demo-skip">Close</button><button class="cbs-demo-primary cbs-demo-start">Start Walkthrough</button></div></section>`;document.body.appendChild(bd);
  const media=bd.querySelector('.cbs-demo-media');if(cfg.videoUrl)media.innerHTML=`<video class="cbs-demo-video" controls playsinline preload="metadata"><source src="${esc(cfg.videoUrl)}"></video>`;else media.innerHTML='<div class="cbs-demo-placeholder"><strong>60-second demo video slot ready.</strong><br>The written walkthrough is active now. A final recorded demo can be added after the interface is locked.</div>';
  const steps=Array.isArray(cfg.steps)?cfg.steps:[];bd.querySelector('.cbs-demo-steps').innerHTML=steps.map((s,i)=>`<div class="cbs-demo-step"><strong>${i+1}. ${esc(s.title||'Step')}</strong><span>${esc(s.text||'')}</span></div>`).join('');
  function close(){if(bd.querySelector('.cbs-demo-dontshow').checked)localStorage.setItem(dismissedKey,'1');bd.classList.remove('open');document.body.style.overflow=''}function open(auto=false){bd.classList.add('open');document.body.style.overflow='hidden';if(auto)localStorage.setItem(seenKey,'1')}
  bd.querySelector('.cbs-demo-close').onclick=close;bd.querySelector('.cbs-demo-skip').onclick=close;bd.addEventListener('click',e=>{if(e.target===bd)close()});bd.querySelector('.cbs-demo-start').onclick=()=>{localStorage.setItem(seenKey,'1');bd.querySelector('.cbs-demo-steps')?.scrollIntoView({behavior:'smooth'});cfg.onStart?.()};
  const target=document.querySelector(cfg.triggerContainer||'.acts')||document.body;const btn=document.createElement('button');btn.type='button';btn.className='cbs-demo-trigger';btn.textContent='How to Use';btn.onclick=()=>open(false);target.appendChild(btn);window.openCactusByteDemo=()=>open(false);
  if(cfg.firstLaunch!==false&&localStorage.getItem(seenKey)!=='1'&&localStorage.getItem(dismissedKey)!=='1')setTimeout(()=>open(true),Number(cfg.autoDelayMs)||900);
})();
